ARG NODE_IMAGE=node:16.15.1-alpine3.16

FROM $NODE_IMAGE AS base
RUN apk --no-cache add dumb-init

RUN mkdir -p /home/node/app && chown node:node /home/node/app
WORKDIR /home/node/app

RUN npm install yarn

USER node

COPY --chown=node:node ./package*.json ./
RUN yarn
COPY --chown=node:node . .

